name: Update copyright list
on:
  - push
jobs:
  copyrights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: |
        ./tools/check_copyrights.sh
    - uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-copyright-list-${{ github.ref }}
        commit-message: 'Update copyright list in license'
        title: 'Update copyright list in license'
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
