name: Fix uses of boost and/or ext namespace
on:
  push:
    branches-ignore:
      - 'dependabot/**'
jobs:
  namespaces:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Check
      run: |
        sed -i -e 's/boost::shared_ptr\b/ext::shared_ptr/g' SWIG/*
        sed -i -e 's/boost::make_shared\b/ext::make_shared/g' SWIG/*
        sed -i -e 's/boost::dynamic_pointer_cast\b/ext::dynamic_pointer_cast/g' SWIG/*
        sed -i -e 's/boost::optional\b/std::optional/g' SWIG/*
        sed -i -e 's/ext::optional\b/std::optional/g' SWIG/*
        sed -i -e 's/boost::none\b/std::nullopt/g' SWIG/*
        sed -i -e 's/ext::nullopt\b/std::nullopt/g' SWIG/*
        sed -i -e 's/boost::any\b/std::any/g' SWIG/*
        sed -i -e 's/ext::any\b/std::any/g' SWIG/*
        sed -i -e 's/boost::any_cast\b/std::any_cast/g' SWIG/*
        sed -i -e 's/ext::any_cast\b/std::any_cast/g' SWIG/*
    - uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ secrets.MACHINE_ACCOUNT_PAT }}
        push-to-fork: ${{ vars.MACHINE_ACCOUNT }}/QuantLib-SWIG
        branch: fix-boost-namespace-${{ github.ref_name }}
        delete-branch: true
        commit-message: 'Fix uses of boost and/or ext namespace'
        title: 'Fix uses of boost and/or ext namespace'
        author: lballabio[bot] <224797326+lballabio-bot@users.noreply.github.com>
